### ISSUE TITLE
2020.11.6 go可信考试参考贴

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/goto#6]
go可信考试

### Golang精编面试题 -- 选择题
https://blog.csdn.net/FHD994603831/article/details/90648525

### Golang精编面试题 -- 判断题
https://blog.csdn.net/fhd994603831/article/details/90708378

### go习题二
https://blog.csdn.net/gongpulin/article/details/78906514

### Go语言（golang）常见问题总结
https://blog.csdn.net/weixin_42117918/article/details/101447064

**Comment by vieyahn2017** [comment]
### Golang 新手要注意的陷阱和常见错误
https://blog.csdn.net/wohu1104/article/details/106391649

### Go的50坑：新Golang开发者要注意的陷阱、技巧和常见错误[2]
https://blog.csdn.net/weixin_30236595/article/details/96446510

**Comment by vieyahn2017** [comment]
### 编码题目，现测

11

```go
package main
import (
    "fmt"
)
func main() {
	x:= [3]int{1,2,3}
	func(arr [3]int) {
		arr[0]=7
		fmt.Println(arr)
	}(x)

    fmt.Println(x)
}



```
[7 2 3]
[1 2 3]




17

```go

package main
import (
    "fmt"
)
func main() {
	
   str:="abc"+"123"
    
  //  str:='abc'+'123'  // invalid character literal (more than one character)
    fmt.Println(str)
    
    fmt.Println( fmt.Sprintf("abc%d",123))
}

```




23

```go
package main
import (
    "fmt"
)

func incr(p int)int {p++
	return *p
}

func main() {
	v:= 1
	incr(&v)
    fmt.Println(v)
}


```
编译报错？
./solution.go:9:9: invalid indirect of p (type int)
./solution.go:14:7: cannot use &v (type *int) as type int in argument to incr



24

```go

package main
import (
    "fmt"
)

func main() {
	s:= "hello,世界"
	r:=[]rune(s)
    fmt.Printf("%d %d", len(s), len(r))
}

```
// 12 8





25

```go
package main
import (
    "fmt"
)

func printAll(vals []interface{}) {
	for _,val:=range vals {
	    fmt.Print(val)
	}
}

func main() {
	names:= []string{"hello", "world"}
    printAll(names)
}

```
编译报错
// cannot use names (type []string) as type []interface {} in argument to printAll




27

```go
package main
import (
    "fmt"
)
func main() {
	
   panic("a")

   defer func() {
   		fmt.Println("b")
   }()
}

```

编译报错，前半句会执行，defer要报错
panic: a

goroutine 1 [running]:
main.main()
	/judger/run/2e4e50544aef46b19812673f50e5da89/solution.go:9 +0x39






57

```go

package main
import (
    "fmt"
)
func main() {
	var a = [] interface{} {1,2,3}
	fmt.Print(a)
	fmt.Print(", ")
	fmt.Println(a...)
}

```

[1 2 3], 1 2 3




60

```go

package main
import (
    "fmt"
    "runtime"
)
func main() {
	runtime.GOMAXPROCS(1)
	go func() {
		for i:=0;i < 10; i++ {
			fmt.Println(i)
		}
	}()

	for {}
}

```

// for{}抢占了CPU，go协程无法执行，无法打印输出
// 去掉后面的for{}也不行

**Comment by vieyahn2017** [comment]
### go整型切片初始化
https://blog.csdn.net/heshuwen/article/details/86602584

```go
/*
 *  go整型切片初始化
 */

s := make([]int, 0)
s := make([]int, ３, ７)
s := []int{７, 2, ５, ６, 5}
```

**Comment by vieyahn2017** [comment]
### goroutine泄露：原理、场景、检测和防范
https://blog.csdn.net/leeright/article/details/94466831

如果你启动了一个 goroutine，但并没有符合预期的退出，直到程序结束，此goroutine才退出，这种情况就是 goroutine 泄露。当 goroutine 泄露发生时，该 goroutine 的栈(一般 2k 内存空间起)一直被占用不能释放，goroutine 里的函数在堆上申请的空间也不能被 垃圾回收器 回收。这样，在程序运行期间，内存占用持续升高，可用内存越来也少，最终将导致系统崩溃。

回顾一下 goroutine 终止的场景：

当一个goroutine完成它的工作
由于发生了没有处理的错误
有其他的协程告诉它终止
那么当这三者同时没发生的时候，就会导致 goroutine 始终不会终止退出。

#### goroutine 泄露的场景
goroutine泄露一般是因为channel操作阻塞而导致整个routine一直阻塞等待或者 goroutine 里有死循环的时候。可以细分为下面五种情况：

1. 从 channel 里读，但是没有写
// leak 是一个有 bug 程序。它启动了一个 goroutine 阻塞接收 channel。当 Goroutine 正在等待时，leak 函数会结束返回。此时，程序的其他任何部分都不能通过 channel 发送数据，那个 channel 永远不会关闭，fmt.Println 调用永远不会发生， 那个 goroutine 会被永远锁死
```go
func leak() {
     ch := make(chan int)

     go func() {
        val := <-ch
        fmt.Println("We received a value:", val)
    }()
}
```

2. 向 unbuffered channel 写，但是没有读

```go
// 一个复杂一点的例子
func sendMsg(msg, addr string) error {
    conn, err := net.Dial("tcp", addr)
    if err != nil {
        return err
    }
    defer conn.Close()
    _, err = fmt.Fprint(conn, msg)
    return err
} 

func broadcastMsg(msg string, addrs []string) error {
    errc := make(chan error)
    for _, addr := range addrs {
        go func(addr string) {
            errc <- sendMsg(msg, addr)
            fmt.Println("done")
        }(addr)
    }

    for _ = range addrs {
        if err := <-errc; err != nil {
            return err
        }
    }
    return nil
}

func main() {
    addr := []string{"localhost:8080", "http://google.com"}
    err := broadcastMsg("hi", addr)

    time.Sleep(time.Second)

    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println("everything went fine")
}

```

对于 broadcastMsg 里的这一段

```go
for _ = range addrs {
        if err := <-errc; err != nil {
            return err
        }
    }
```

当遇到 第一条不为 nil 的 err，broadcastMsg就返回了，那么从第二个调用 sendMsg 后返回值 err 不为 nil 的 goroutine 在 errc <- sendMsg(msg, addr)这里都将阻塞而造成这些 goroutine 不能退出。

3. 向已满的 buffered channel 写，但是没有读
和第二种情况比较类似。

在 channel 的接收值数量有限，且可以用 buffered channel 的情况下，那 buffer size 就分配的和 接收值数量 一样，这样可以解决掉第2、3种原因造成的泄露。比如在第二种中，改成
```go
errc := make(chan error, len(addrs))
```
问题就解决了。

注意：time package里的定时器使用不当也会造成 goroutine 泄露。
```go
  tick := time.Tick(1 * time.Second)
	for countdown := 10; countdown > 0; countdown-- {
		fmt.Println(countdown)
		select {
		case <-tick:
			// Do nothing.
		case <-abort:
			fmt.Println("aborted!")
			return
		}
	}
```

以上的代码中，当 for 循环结束后，tick 将不再有接收者，time.Tick 启动的 goroutine 将产生泄露。

建议在程序的整个生命周期需要 ticks 时才使用 time.Tick，否则建议按如下模式使用：

```go
	ticker := time.NewTicker(1 * time.Second)
	<- ticker.C 
	ticker.Stop() // 当不再使用后，结束 ticker 的 goroutine
```

4. select操作在所有case上阻塞
实现一个 fibonacci 数列生成器，并在独立的 goroutine 中运行，在读取完需要长度的数列后，如果 用于 退出生成器的 quit 忘了被 close (或写入数据)，select 将一直被阻塞造成 该 goroutine 泄露。
```go
func fibonacci(c, quit chan int)  {
	x, y := 0, 1
	for{
		select {
		case c <- x:
			x, y = y, x+y
		case <-quit:
			fmt.Println("quit")
			return
		}
	}
}

func main() {
	c := make(chan int)
	quit := make(chan int)

	go fibonacci(c, quit)

	for i := 0; i < 10; i++{
		fmt.Println(<- c)
	}
	
  // close(quit)
}

```

在这种需要一个独立的 goroutine 作为生成器的场景下，为了能在外部结束这个 goroutine，我们通常有两种方法：

使用上述实现里的模式，传入一个 quit channel，配合 select，当不需要的时候，close 这个 quit channel，该 goroutine 就可以退出。
使用 context 包：
```go
func fibonacci(c chan int, ctx context.Context)  {
	x, y := 0, 1
	for{
		select {
		case c <- x:
			x, y = y, x+y
		case <-ctx.Done():
			fmt.Println("quit")
			return
		}
	}
}

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	c := make(chan int)

	go fibonacci(c, ctx)

	for i := 0; i < 10; i++{
		fmt.Println(<- c)
	}

	cancel()

	time.Sleep(5 * time.Second)
}

```

5. goroutine进入死循环中，导致资源一直无法释放
通常由于代码里循环的退出条件实现的不对，导致死循环。

// 粗暴的示例
```go
func foo() {
  for{
    fmt.Println("fooo")
  }
}
```

#### goroutine 泄露检测和定位
监控工具：固定周期对进程的内存占用情况进行采样，数据可视化后，根据内存占用走势（持续上升），很容易发现是否发生内存泄露。可以使用云服务提供的内存使用监控服务或者自己实现一个 daemon 脚本周期采集内存占用数据。
使用Go提供的pprof工具分析是否发生内存泄露。使用 pprof 的 heap 能够获取程序运行时的内存信息，通过对运行的程序多次采样对比，分析出内存的使用情况。
这篇文章 有关于检测和定位更详细的描述，可以参考，本处不再累述。

#### goroutine 泄露的防范
创建goroutine时就要想好该goroutine该如何结束

使用channel时，要考虑到 channel 阻塞时协程可能的行为

实现循环语句时注意循环的退出条件，避免死循环

**Comment by vieyahn2017** [comment]
### golang interface判断为空nil
https://blog.csdn.net/lanyang123456/article/details/83715090

要判断interface 空的问题，首先看下其底层实现。

interface 底层结构
根据 interface 是否包含有 method，底层实现上用两种 struct 来表示：iface 和 eface。eface表示不含 method 的 interface 结构，或者叫 empty interface。对于 Golang 中的大部分数据类型都可以抽象出来 _type 结构，同时针对不同的类型还会有一些其他信息。


总结

一个接口包括动态类型和动态值。
如果一个接口的动态类型和动态值都为空，则这个接口为空的。








### go interface{}==nil 几种坑及原理
https://blog.csdn.net/yonggeit/article/details/102586637

本文是Go比较有名的一个坑，在以前面试的时候也被问过，为什么想起来写这个？

因为我们线上就真实出现过这个坑,写给不了解的人在使用 if err != nil 的时候提高警惕。

Go语言的interface{}在使用过程中有一个特别坑的特性，当你比较一个interface{}类型的值是否是nil的时候，这是需要特别注意避免的问题。

**Comment by vieyahn2017** [comment]
### go中的main函数和init函数
https://blog.csdn.net/cs380637384/article/details/81206237

Go里面有两个保留的函数：init函数（能够应用于所有的package）和main函数（只能应用于package main）。这两个函数在定义时不能有任何的参数和返回值。虽然一个package里面可以写任意多个init函数，但这无论是对于可读性还是以后的可维护性来说，我们都强烈建议用户在一个package中每个文件只写一个init函数。

Go程序会自动调用init()和main()，所以你不需要在任何地方调用这两个函数。每个package中的init函数都是可选的，但package main就必须包含一个main函数。

程序的初始化和执行都起始于main包。如果main包还导入了其它的包，那么就会在编译时将它们依次导入。有时一个包会被多个包同时导入，那么它只会被导入一次（例如很多包可能都会用到fmt包，但它只会被导入一次，因为没有必要导入多次）。当一个包被导入时，如果该包还导入了其它的包，那么会先将其它包导入进来，然后再对这些包中的包级常量和变量进行初始化，接着执行init函数（如果有的话），依次类推。等所有被导入的包都加载完毕了，就会开始对main包中的包级常量和变量进行初始化，然后执行main包中的init函数（如果存在的话），最后执行main函数。

**Comment by vieyahn2017** [comment]
### Go 性能测试工具PProf
https://blog.csdn.net/guyan0319/article/details/85007181

Go语言自带了强大的性能测试工具pprof,位于 net/http 包下的 pprof。 官方文档

PProf 关注的模块
CPU profile：报告程序的 CPU 使用情况，按照一定频率去采集应用程序在 CPU 和寄存器上面的数据
Memory Profile（Heap Profile）：报告程序的内存使用情况
Block Profiling：报告 goroutines 不在运行状态的情况，可以用来分析和查找死锁等性能瓶颈
Goroutine Profiling：报告 goroutines 的使用情况，有哪些 goroutine，它们的调用关系是怎样的



### Golang 使用pprof监控性能及GC调优先
https://blog.csdn.net/lengyuezuixue/article/details/79753118

**Comment by vieyahn2017** [comment]
### GO select用法详解
https://blog.csdn.net/zl1zl2zl3/article/details/80432779

golang 的 select 就是监听 IO 操作，当 IO 操作发生时，触发相应的动作。 

在执行select语句的时候，运行时系统会自上而下地判断每个case中的发送或接收操作是否可以被立即执行(立即执行：意思是当前Goroutine不会因此操作而被阻塞)

select的用法与switch非常类似，由select开始一个新的选择块，每个选择条件由case语句来描述。与switch语句可以选择任何可使用相等比较的条件相比，select有比较多的限制，其中最大的一条限制就是每个case语句里必须是一个IO操作，确切的说，应该是一个面向channel的IO操作。

下面这段话来自官方文档：

A "select" statement chooses which of a set of possible send or receive operations will proceed. It looks similar to a "switch" statement but with the cases all referring to communication operations.


Execution of a "select" statement proceeds in several steps:

1、For all the cases in the statement, the channel operands of receive operations and the channel and right-hand-side expressions of send statements are evaluated exactly once, in source order, upon entering the "select" statement.(所有channel表达式都会被求值、所有被发送的表达式都会被求值。求值顺序：自上而下、从左到右)

2、If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection. Otherwise, if there is a default case, that case is chosen. If there is no default case, the "select" statement blocks until at least one of the communications can proceed.（如果有一个或多个IO操作可以完成，则Go运行时系统会随机的选择一个执行，否则的话，如果有default分支，则执行default分支语句，如果连default都没有，则select语句会一直阻塞，直到至少有一个IO操作可以进行）

3、Unless the selected case is the default case, the respective communication operation is executed.

4、If the selected case is a RecvStmt with a short variable declaration or an assignment, the left-hand side expressions are evaluated and the received value (or values) are assigned.

5、The statement list of the selected case is executed.

Since communication on nil channels can never proceed, a select with only nil channels and no default case blocks forever.

 

可以使用break语句来终止select语句的执行。

 

示例1：select语句会一直等待，直到某个case里的IO操作可以进行

//main.go

```go
package main
 
import "fmt"
import "time"
 
func f1(ch chan int) {
    time.Sleep(time.Second * 5)
    ch <- 1
}
 
func f2(ch chan int) {
    time.Sleep(time.Second * 10)
    ch <- 1
}
 
func main() {
    var ch1 = make(chan int)
    var ch2 = make(chan int)
    go f1(ch1)
    go f2(ch2)
    select {
    case <-ch1:
        fmt.Println("The first case is selected.")
    case <-ch2:
        fmt.Println("The second case is selected.")
    }
}

```

编译运行：


C:/go/bin/go.exe run test14.go [E:/project/go/proj/src/test]

The first case is selected.

成功: 进程退出代码 0.
如果把f2中的时间改成2s，则输出The second case is selected.
 

示例2：所有跟在case关键字右边的发送语句或接收语句中的通道表达式和元素表达式都会先被求值。无论它们所在的case是否有可能被选择都会这样。 


求值顺序：自上而下、从左到右 

此示例使用空值channel进行验证。

//main.go

```go
package main
 
import (
    "fmt"
)
 
//定义几个变量，其中chs和numbers分别代表通道列表和整数列表
var ch1 chan int
var ch2 chan int
var chs = []chan int{ch1, ch2}
var numbers = []int{1, 2, 3, 4, 5}
 
func main() {
    select {
    case getChan(0) <- getNumber(2):
        fmt.Println("1th case is selected.")
    case getChan(1) <- getNumber(3):
        fmt.Println("2th case is selected.")
    default:
        fmt.Println("default!.")
    }
}
 
func getNumber(i int) int {
    fmt.Printf("numbers[%d]\n", i)
    return numbers[i]
}
 
func getChan(i int) chan int {
    fmt.Printf("chs[%d]\n", i)
    return chs[i]
}


```

编译运行：

C:/go/bin/go.exe run test4.go [E:/project/go/proj/src/test]

chs[0]
numbers[2]
chs[1]
numbers[3]
default!.

成功: 进程退出代码 0.

上面的案例，之所以输出default!.是因为chs[0]和chs[1]都是空值channel，和空值channel通信永远都不会成功。

 

示例3：所有跟在case关键字右边的发送语句或接收语句中的通道表达式和元素表达式都会先被求值。无论它们所在的case是否有可能被选择都会这样。 

求值顺序：自上而下、从左到右 

此示例使用非空值channel进行验证。

//main.go

 
```go
package main
 
import (
    "fmt"
)
 
//定义几个变量，其中chs和numbers分别代表通道列表和整数列表
var ch1 chan int = make(chan int, 1)  //声明并初始化channel变量
var ch2 chan int = make(chan int, 1)  //声明并初始化channel变量
var chs = []chan int{ch1, ch2}
var numbers = []int{1, 2, 3, 4, 5}
 
func main() {
    select {
    case getChan(0) <- getNumber(2):
        fmt.Println("1th case is selected.")
    case getChan(1) <- getNumber(3):
        fmt.Println("2th case is selected.")
    default:
        fmt.Println("default!.")
    }
}
 
func getNumber(i int) int {
    fmt.Printf("numbers[%d]\n", i)
    return numbers[i]
}
 
func getChan(i int) chan int {
    fmt.Printf("chs[%d]\n", i)
    return chs[i]
}

```

编译运行：
 
C:/go/bin/go.exe run test4.go [E:/project/go/proj/src/test]

chs[0]
numbers[2]
chs[1]
numbers[3]
1th case is selected.

成功: 进程退出代码 0.

此示例，使用非空值channel进行IO操作，所以可以成功，没有走default分支。

 
示例4：如果有多个case同时可以运行，go会随机选择一个case执行
//main.go
```go
package main
 
import (
    "fmt"
)
 
func main() {
    chanCap := 5
    ch := make(chan int, chanCap) //创建channel，容量为5
 
    for i := 0; i < chanCap; i++ { //通过for循环，向channel里填满数据
        select { //通过select随机的向channel里追加数据
        case ch <- 1:
        case ch <- 2:
        case ch <- 3:
        }
    }
 
    for i := 0; i < chanCap; i++ {
        fmt.Printf("%v\n", <-ch)
    }
}
```

编译运行：

 
C:/go/bin/go.exe run test5.go [E:/project/go/proj/src/test]

2
1
2
1
1

成功: 进程退出代码 0.

注意：上面的案例每次运行结果都不一样。

 
 
 

示例5：使用break终止select语句的执行

```go
package main
 
import "fmt"
 
func main() {
    var ch = make(chan int, 1)
 
    ch <- 1
 
    select {
    case <-ch:
        fmt.Println("This case is selected.")
        break //The following statement in this case will not execute.
        fmt.Println("After break statement")
    default:
        fmt.Println("This is the default case.")
    }
 
    fmt.Println("After select statement.")
}
 
```
 

编译运行：

 

C:/go/bin/go.exe run test15.go [E:/project/go/proj/src/test]

This case is selected.
After select statement.
成功: 进程退出代码 0.






### select 典型用法
来自 https://blog.csdn.net/zhaominpro/article/details/77570290

1.超时判断

```go
//比如在下面的场景中，使用全局resChan来接受response，如果时间超过3S,resChan中还没有数据返回，则第二条case将执行
var resChan = make(chan int)
// do request
func test() {
	select {
	case data := <-resChan:
		doData(data)
	case <-time.After(time.Second * 3):
		fmt.Println("request time out")
	}
}

func doData(data int) {
    //...
}

```

2.退出

//主线程（协程）中如下：

```go
var shouldQuit=make(chan struct{})
fun main(){
    {
        //loop
    }
    //...out of the loop
    select {
		case <-c.shouldQuit:
			cleanUp()
			return
		default:
		}
    //...
}

//再另外一个协程中，如果运行遇到非法操作或不可处理的错误，就向shouldQuit发送数据通知程序停止运行
close(shouldQuit)

```

3.判断channel是否阻塞

```go
//在某些情况下是存在不希望channel缓存满了的需求的，可以用如下方法判断
ch := make (chan int, 5)
//...
data：=0
select {
case ch <- data:
default:
    //做相应操作，比如丢弃data。视需求而定
}

```



举一个有趣的列子：使用channel将异步变为同步

题目如下：
存在以下代码，请问如何实现print函数可以顺序输出1~75，要求不使用锁，只能使用channel

```go

package main
 
import "fmt"
import "time"

func main() {
	for i := 1; i < 75; i++ {
		go print(i)
	}
	time.Sleep(5*time.Second) // wait all goroutine
}

func print(i int) { 
    fmt.Println(i)
}


```

以上代码正常执行结果是无序的
1
38
50
...
32




实现有序的方法：
实现完整代码如下：

```go
package main

import (
	"fmt"
	"time"
)

var ch = make(chan int)

func main() {
	for i := 1; i <= 75; i++ {
		go print(i)
		ch <- 0
	}
	time.Sleep(5 * time.Second) //wait all goroutines
}

func print(i int) {
	<-ch
	fmt.Println(i)
}

```

**Comment by vieyahn2017** [comment]
### go语言中的switch语句？

单个case中，可以出现多个结果选项

只有在case中明确添加fallthrough关键字，才会继续执行紧跟的下一个case

case 后面不需要带break , 程序匹配到一个case 后就会执行对应的代码块，然后退出switch，如
果一个都匹配不到，则执行default。



### switch 的使用的注意事项和细节
1、case/switch 后是一个表达式( 即：常量值、变量、一个有返回值的函数等都可以)。
2、case 后的各个表达式的值的数据类型，必须和switch 的表达式数据类型一致。
3、case 后面可以带多个表达式，使用逗号间隔。比如 case 表达式 1, 表达式 2 ...。

    var n1 int32 =5
    var n2 int32 = 20

    switch  n1 {
    case n2,10,5://case后面可以有多个表达式
        fmt.Println("ok1~")
    default:
        fmt.Println("没有匹配到~")
    }
4、case 后面的表达式如果是常量值(字面量)，则要求不能重复。
5、case 后面不需要带break , 程序匹配到一个case 后就会执行对应的代码块，然后退出switch，如
果一个都匹配不到，则执行default。
6、default 语句不是必须的。
7、switch后也可以不带表达式，类似if --else分支来使用。

var score int = 90
    switch  {
    case score >90:
        fmt.Println("成绩优秀")
    case score >=70 && score <=90:
        fmt.Println("成绩优良")
    case score >=60 && score <70 :
        fmt.Println("成绩及格")
    default:
        fmt.Println("不及格")
    }
8、switch 后也可以直接声明/定义一个变量，分号结束，不推荐。

    //这种方式不建议使用
    switch grade :=90;  {
    case grade >90:
        fmt.Println("成绩优秀~")
    case grade >=70 && score <=90:
        fmt.Println("成绩优良~")
    case grade >=60 && score <70 :
        fmt.Println("成绩及格~")
    default:
        fmt.Println("不及格~")
    }
9、switch穿透 fallthrough，如果在case 语句块后增加fallthrough ,则会继续执行下一个case，也
叫switch 穿透。

    var num int = 10
    switch num {
    case 10:
        fmt.Println("ok1")
        fallthrough//默认只能穿透一层
    case 20:
        fmt.Println("ok2")
        fallthrough
    case 30:
        fmt.Println("ok3")
    default:
        fmt.Println("null....")
    }
10、Type Switch：switch语句还可以被用于type-switch 来判断某个interface 变量中实际指向的
变量类型

var x interface{}
    var y = 10.0
    x = y
    switch i := x.(type){
    case nil:
        fmt.Printf(" x 的类型~ : %T",i)
    case int:
        fmt.Printf(" x 是 int 型")
    case float64:
        fmt.Printf(" x 是 float64 型")
    case func(int) float64:
        fmt.Printf(" x 是 func(int) 型")
    case bool,string:
        fmt.Printf(" x 是 bool 型 或 string  型")
    default:
        fmt.Printf("未知型")
            
    }

**Comment by vieyahn2017** [comment]
## Go语言（golang）常见问题总结（一）

cqu_jiangzhou 2019-09-26 17:03:53  170  收藏
版权
1. 在go语言中，new和make的区别？
new 的作用是初始化一个指向类型的指针(*T)

new函数是内建函数，函数定义：func new(Type) *Type

使用new函数来分配空间。传递给new 函数的是一个类型，不是一个值。返回值是 指向这个新分配的零值的指针。

make 的作用是为 slice，map 或 chan 初始化并返回引用(T)。

make函数是内建函数，函数定义：func make(Type, size IntegerType) Type

  第一个参数是一个类型，第二个参数是长度
返回值是一个类型
make(T, args)函数的目的与new(T)不同。它仅仅用于创建 Slice, Map 和 Channel，并且返回类型是 T（不是T*）的一个初始化的（不是零值）的实例。


栈和堆变量
level: advanced
你并不总是知道变量是分配到栈还是堆上。在C++中，使用 new创建的变量总是在堆上。在Go中，即使是使用 new()或者 make()函数来分配，变量的位置还是由编译器决定。编译器根据变量的大小和“泄露分析”的结果来决定其位置。这也意味着在局部变量上返回引用是没问题的，而这在C或者C++这样的语言中是不行的。



 

2. 在go语言中，Printf()、Sprintf()、Fprintf()函数的区别用法是什么？
都是把格式好的字符串输出，只是输出的目标不一样：

Printf()，是把格式字符串输出到标准输出（一般是屏幕，可以重定向）。

Printf() 是和标准输出文件(stdout)关联的,Fprintf 则没有这个限制.

 

Sprintf()，是把格式字符串输出到指定字符串中，所以参数比printf多一个char*。那就是目标字符串地址。

 

Fprintf()， 是把格式字符串输出到指定文件设备中，所以参数笔printf多一个文件指针FILE*。主要用于文件操作。Fprintf()是格式化输出到一个stream，通常是到文件。

 

3. 说说go语言中，数组与切片的区别？
(1). 数组
数组是具有固定长度且拥有零个或者多个相同数据类型元素的序列。
数组的长度是数组类型的一部分，所以[3]int 和 [4]int 是两种不同的数组类型。

  数组需要指定大小，不指定也会根据初始化的自动推算出大小，不可改变 ;

  数组是值传递;

  数组是内置(build-in)类型,是一组同类型数据的集合，它是值类型，通过从0开始的下标索引访问元素值。在初始化后长度是固定的，无法修改其长度。当作为方法的参数传入时将复制一份数组而不是引用同一指针。数组的长度也是其类型的一部分，通过内置函数len(array)获取其长度。

  数组定义：var array [10]int

            var array = [5]int{1,2,3,4,5}

 

(2). 切片
切片表示一个拥有相同类型元素的可变长度的序列。
切片是一种轻量级的数据结构，它有三个属性：指针、长度和容量。

切片不需要指定大小;

切片是地址传递;

切片可以通过数组来初始化，也可以通过内置函数make()初始化 .初始化时len=cap,在追加元素时如果容量cap不足时将按len的2倍扩容；

切片定义：var slice []type = make([]type, len)

 

4. 解释以下命令的作用？
go env:   #用于查看go的环境变量

go run:   #用于编译并运行go源码文件

go build:  #用于编译源码文件、代码包、依赖包

go get:   #用于动态获取远程代码包

go install:  #用于编译go文件，并将编译结构安装到bin、pkg目录

go clean:  #用于清理工作目录，删除编译和安装遗留的目标文件

go version:  #用于查看go的版本信息

 

5. 说说go语言中的协程？
协程和线程都可以实现程序的并发执行；

通过channel来进行协程间的通信；

只需要在函数调用前添加go关键字即可实现go的协程，创建并发任务；

关键字go并非执行并发任务，而是创建一个并发任务单元；

 

6. 说说go语言中的for循环？
for循环支持continue和break来控制循环，但是它提供了一个更高级的break，可以选择中断哪一个循环
for循环不支持以逗号为间隔的多个赋值语句，必须使用平行赋值的方式来初始化多个变量 

 

7. 说说go语言中的switch语句？
单个case中，可以出现多个结果选项

只有在case中明确添加fallthrough关键字，才会继续执行紧跟的下一个case

 

8. go语言中没有隐藏的this指针，这句话是什么意思？
方法施加的对象显式传递，没有被隐藏起来

golang的面向对象表达更直观，对于面向过程只是换了一种语法形式来表达

方法施加的对象不需要非得是指针，也不用非得叫this

 

9. go语言中的引用类型包含哪些？
数组切片、字典(map)、通道（channel）、接口（interface）

 

10. go语言中指针运算有哪些？
可以通过“&”取指针的地址

可以通过“*”取指针指向的数据

 

11.说说go语言的main函数
main函数不能带参数

main函数不能定义返回值

main函数所在的包必须为main包

main函数中可以使用flag包来获取和解析命令行参数

 

12. 说说go语言的同步锁？
(1) 当一个goroutine获得了Mutex后，其他goroutine就只能乖乖的等待，除非该goroutine释放这个Mutex

(2) RWMutex在读锁占用的情况下，会阻止写，但不阻止读

(3) RWMutex在写锁占用情况下，会阻止任何其他goroutine（无论读和写）进来，整个锁相当于由该goroutine独占

 

13. 说说go语言的channel特性？
A. 给一个 nil channel 发送数据，造成永远阻塞

B. 从一个 nil channel 接收数据，造成永远阻塞

C. 给一个已经关闭的 channel 发送数据，引起 panic

D. 从一个已经关闭的 channel 接收数据，如果缓冲区中为空，则返回一个零值

E. 无缓冲的channel是同步的，而有缓冲的channel是非同步的

 

14. go语言触发异常的场景有哪些？
A. 空指针解析

B. 下标越界

C. 除数为0

D. 调用panic函数



17. go语言中，GoStub的作用是什么？
A. GoStub可以对全局变量打桩

B. GoStub可以对函数打桩

C. GoStub不可以对类的成员方法打桩

D. GoStub可以打动态桩，比如对一个函数打桩后，多次调用该函数会有不同的行为
